language: node_js
node_js: 
    - "8"
before_install:
    - git config --global user.email $GITHUB_EMAIL
    - git config --global user.name $GITHUB_USERNAME
    - npm i hexo-cli -g
    - git clone $THEME_URI themes/$THEME_NAME
script:
    - hexo config theme $THEME_NAME
    - hexo generate
after_success:
    - cd public
    - git init
    - git add .
    - git commit -m "Travis Deploy"
    - git push -f -q https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/blog master:gh-pages
